param(
    [string]$AssetDirectory = (Join-Path $PSScriptRoot '..\assets\lang'),
    [string]$Output = (Join-Path $PSScriptRoot '..\src\ui\i18n_generated.cpp')
)

# Parses assets/lang/*.xml (build-time source, translator-editable) and emits
# src/ui/i18n_generated.cpp: a C++ byte table compiled straight into the
# binary. Mirrors imgui_md2/scripts/generate_embedded_fonts.ps1's approach of
# "commit the generated .cpp, let xmake glob pick it up" -- no new library
# dependency, zero XML parsing at runtime, RAM cost is just .rodata pages.
#
# Each (language, key) value is emitted as a null-terminated byte array from
# its raw UTF-8 bytes (via [System.Text.Encoding]::UTF8.GetBytes()) rather
# than as a C string literal. This sidesteps C++ source-encoding and string-
# escaping pitfalls entirely -- the same reasoning generate_embedded_fonts.ps1
# applies to font blobs, extended here to (non-ASCII-capable) text. Language
# display names (e.g. "简体中文") get the same treatment for the same reason;
# keys and language codes are plain ASCII identifiers, so those are emitted as
# ordinary C string literals.

$ErrorActionPreference = 'Stop'

function Get-CIdentifier([string]$Text) {
    $sb = New-Object System.Text.StringBuilder
    foreach ($ch in $Text.ToCharArray()) {
        if ($ch -match '[A-Za-z0-9_]') {
            [void]$sb.Append($ch)
        } else {
            [void]$sb.Append('_')
        }
    }
    return $sb.ToString()
}

function Write-Utf8ByteArray([System.IO.StreamWriter]$Writer, [string]$Symbol, [string]$Text) {
    # `unsigned char`, not `char`: bytes >= 0x80 (any non-ASCII UTF-8 content)
    # are not representable in a (default-signed) `char` brace-initializer
    # without a narrowing-conversion error under C++11 list-initialization
    # rules. Callers needing `const char*` (the public accessor type) get
    # there via reinterpret_cast at the point of use, same as one would cast
    # any raw byte buffer to a string pointer.
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $Writer.WriteLine("static const unsigned char ${Symbol}[] = {")
    $line = New-Object System.Collections.Generic.List[string]
    foreach ($b in $bytes) {
        $line.Add(('0x{0:X2}' -f $b))
    }
    $line.Add('0x00')
    for ($index = 0; $index -lt $line.Count; $index += 16) {
        $last = [Math]::Min($index + 16, $line.Count) - 1
        $chunk = $line.GetRange($index, $last - $index + 1)
        $Writer.WriteLine('    ' + ($chunk -join ', ') + ',')
    }
    $Writer.WriteLine('};')
}

if (!(Test-Path -LiteralPath $AssetDirectory -PathType Container)) {
    throw "Language asset directory not found: $AssetDirectory"
}

$xmlFiles = Get-ChildItem -LiteralPath $AssetDirectory -Filter '*.xml' | Sort-Object Name
if ($xmlFiles.Count -eq 0) {
    throw "No language XML files found in: $AssetDirectory"
}

# languages: ordered list of @{ Code=; Name=; Values=@{key=value} }
$languages = @()
$allKeys = New-Object System.Collections.Generic.HashSet[string]

foreach ($file in $xmlFiles) {
    [xml]$xml = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $root = $xml.language
    if ($null -eq $root) {
        throw "Missing <language> root element in: $($file.FullName)"
    }
    $code = $root.code
    $name = $root.name
    if ([string]::IsNullOrWhiteSpace($code)) {
        throw "Missing code attribute in: $($file.FullName)"
    }

    $values = @{}
    foreach ($node in $root.string) {
        $key = $node.key
        if ([string]::IsNullOrWhiteSpace($key)) {
            throw "Missing key attribute on <string> in: $($file.FullName)"
        }
        $values[$key] = [string]$node.'#text'
        [void]$allKeys.Add($key)
    }

    $languages += [pscustomobject]@{
        Code   = $code
        Name   = $name
        Values = $values
    }
}

if (-not ($languages | Where-Object { $_.Code -eq 'en' })) {
    throw "Language pack with code='en' is required as the fallback language."
}

$sortedKeys = $allKeys | Sort-Object -Culture 'en-US'

$parent = Split-Path -Parent $Output
New-Item -ItemType Directory -Force -Path $parent | Out-Null
$writer = [System.IO.StreamWriter]::new($Output, $false, [System.Text.UTF8Encoding]::new($false))
try {
    $writer.WriteLine('// Generated by scripts/generate_embedded_languages.ps1 from assets/lang/*.xml.')
    $writer.WriteLine('// Do not edit by hand -- edit the XML sources and re-run the generator.')
    $writer.WriteLine('#include "ui/i18n_generated.h"')
    $writer.WriteLine('')
    $writer.WriteLine('namespace ui::i18n_gen {')
    $writer.WriteLine('namespace {')
    $writer.WriteLine('')

    $writer.WriteLine('const char* const s_keys[] = {')
    foreach ($key in $sortedKeys) {
        $escaped = $key.Replace('\', '\\').Replace('"', '\"')
        $writer.WriteLine("    ""${escaped}"",")
    }
    $writer.WriteLine('};')
    $writer.WriteLine('constexpr int kKeyCount = sizeof(s_keys) / sizeof(s_keys[0]);')
    $writer.WriteLine('')

    foreach ($lang in $languages) {
        $langId = Get-CIdentifier $lang.Code
        $writer.WriteLine("// Language: $($lang.Code) ($($lang.Name))")
        $keyIndex = 0
        foreach ($key in $sortedKeys) {
            if ($lang.Values.ContainsKey($key)) {
                $symbol = "s_val_${langId}_${keyIndex}"
                Write-Utf8ByteArray $writer $symbol $lang.Values[$key]
            }
            $keyIndex++
        }
        Write-Utf8ByteArray $writer "s_langname_${langId}" $lang.Name
        $writer.WriteLine("const char* const s_values_${langId}[] = {")
        $keyIndex = 0
        foreach ($key in $sortedKeys) {
            if ($lang.Values.ContainsKey($key)) {
                $writer.WriteLine("    reinterpret_cast<const char*>(s_val_${langId}_${keyIndex}),")
            } else {
                $writer.WriteLine('    nullptr,')
            }
            $keyIndex++
        }
        $writer.WriteLine('};')
        $writer.WriteLine('')
    }

    $writer.WriteLine('const char* const s_lang_codes[] = {')
    foreach ($lang in $languages) {
        $escapedCode = $lang.Code.Replace('\', '\\').Replace('"', '\"')
        $writer.WriteLine("    ""${escapedCode}"",")
    }
    $writer.WriteLine('};')
    $writer.WriteLine('')

    $writer.WriteLine('const char* const s_lang_names[] = {')
    foreach ($lang in $languages) {
        $langId = Get-CIdentifier $lang.Code
        $writer.WriteLine("    reinterpret_cast<const char*>(s_langname_${langId}),")
    }
    $writer.WriteLine('};')
    $writer.WriteLine('')

    $writer.WriteLine('const char* const* const s_lang_values[] = {')
    foreach ($lang in $languages) {
        $langId = Get-CIdentifier $lang.Code
        $writer.WriteLine("    s_values_${langId},")
    }
    $writer.WriteLine('};')
    $writer.WriteLine('constexpr int kLangCount = sizeof(s_lang_codes) / sizeof(s_lang_codes[0]);')
    $writer.WriteLine('')
    $writer.WriteLine('} // namespace')
    $writer.WriteLine('')

    $writer.WriteLine('int KeyCount() { return kKeyCount; }')
    $writer.WriteLine('const char* Key(int i) { return (i >= 0 && i < kKeyCount) ? s_keys[i] : nullptr; }')
    $writer.WriteLine('int LanguageCount() { return kLangCount; }')
    $writer.WriteLine('const char* LangCode(int lang) { return (lang >= 0 && lang < kLangCount) ? s_lang_codes[lang] : nullptr; }')
    $writer.WriteLine('const char* LangName(int lang) { return (lang >= 0 && lang < kLangCount) ? s_lang_names[lang] : nullptr; }')
    $writer.WriteLine('const char* Value(int lang, int key_index) {')
    $writer.WriteLine('    if (lang < 0 || lang >= kLangCount || key_index < 0 || key_index >= kKeyCount) return nullptr;')
    $writer.WriteLine('    return s_lang_values[lang][key_index];')
    $writer.WriteLine('}')
    $writer.WriteLine('')
    $writer.WriteLine('} // namespace ui::i18n_gen')
} finally {
    $writer.Dispose()
}

Write-Host "Generated $Output ($($languages.Count) language(s), $($sortedKeys.Count) key(s))"
